### ISSUE TITLE
Set up your init.caffemodel at deeplab/exper/voc12/model/deeplab_largeFOV. What does this exactly means?

### ISSUE THREAD

**Issue by lingerois** [josephuan/my_deeplab-public-ver2#1]
How to get a .caffemodel file before trainning? Can anybody explain what does the confusing phrase "set up" exactly means?

**Comment by josephuan** [comment]
you could visit http://liangchiehchen.com/projects/DeepLab_Models.html to get required model

**Comment by lingerois** [comment]
Thanks, so the model must be pre-defined ones.
